DB_CONNECTION: mysql
DB_HOST: 4dgq50mzjncy.ap-northeast-2.psdb.cloud
DB_PORT: 3306
DB_DATABASE: mailbox
DB_USERNAME: cops8unptiqv
DB_PASSWORD: pscale_pw_DFNcAQKJ13ke_rc-venRRqR3lPBG2Gsngpe15e4nZbA
MYSQL_ATTR_SSL_CA: /var/task/ca-certificates.crt
