name: client deploy
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
    - uses: actions/checkout@v2
      with:
        SLS_INTERACTIVE_SETUP_ENABLE: 1
    - name: configure aws
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: composer install
      run: composer install -n --prefer-dist
    - name: copy .env
      run: cp .env.example .env
    - name: generate key
      run: php artisan key:generate
    - name: copy secret.yml
      run: aws s3 cp s3://secret-mailbox-yappi/secret.yml "config/"
    - name: deploy public files
      run: aws s3 cp public s3://mailbox-yappi/  --recursive
    - name: setup node.js
      uses: actions/setup-node@v1
    - name: install sls
      run: npm i -g serverless
    - name: deploy
      run: serverless deploy --stage prod